[package]
name = "weight_experiment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "weight_experiment"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
pathfinding = "4.8.2"
rayon = "1.8"